### ISSUE TITLE
How to start situation service in 8000 port

### ISSUE THREAD

**Issue by rinshadka** [situation-sh/situation#10]
Hi,

I have came across this software  and would love to explore more on its capacity in parallel to osquery. while going through the documentation I could find all the API request sample via `curl` , but couldn't understand how to start the service. 

Tried,

`situation --backends.http.enabled=true --backends.http.url=http://localhost:8000/situation/ --backends.http.method=POST --backends.http.header.content-type=application/json --backends.http.header.authorization="Bearer qwerty123456"`

But it just exited by outputting a json data.

Thanks.

**Comment by asiffer** [comment]
Hi, sorry for the huge delay,  I did not get the notification. Actually, this is a single binary that collects and then send data wherever you want (stdout, file or API endpoint). You have to write your own backend if you want to analyze/store/... these data (there is the json schema and you can use code generator like https://github.com/koxudaxi/datamodel-code-generator)
